environment:
  global:
    test: bla
    host:
      secure: w/DTEzu1t/sp9qUGZlRiBD17VG4I4w1k9uPFf5agU18=
    password:
      secure: TT5cKTVom4VTJrtg5NSU6g==
notifications:
  - provider: GitHubPullRequest

build_script:
  - cd C:\
  - IF "%test%"=="bla" (
    echo fine
    echo very fine
    )
artifacts:
  - path: test.txt
    name: artifact
    
