notifications:
  - provider: GitHubPullRequest
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"

build_script:
  - cd C:\
test_script:
  - echo "Hello, world"
artifacts:
  - path: test.txt
    name: artifact