environment:
  global:
    my_var:
      secure: jw6zPox7McM4+aag8F8/Gw==
    QT: 5.0

build_script:
  - echo %APPVEYOR_REPO_COMMIT%
  - echo %APPVEYOR_REPO_COMMIT:~0,7%
  - git log >> log.txt
artifact:
  - log.txt
