environment:
  global:
    host: w/DTEzu1t/sp9qUGZlRiBD17VG4I4w1k9uPFf5agU18=
    password: TT5cKTVom4VTJrtg5NSU6g==
notifications:
  - provider: GitHubPullRequest

build_script:
  - cd C:\
test_script:
  - C:/msys64/usr/bin/pacman -Su --noconfirm sshpass
  - C:/msys64/usr/bin/sshpass -p "%password%" C:/msys64/usr/bin/scp /t/test/test_dir1.zip %host%:/home/devops/dl/ts/fresh/
artifacts:
  - path: test.txt
    name: artifact
    
