environment:
  global:
    MINGW: C:\Qt\Tools\mingw530_32
    QTDIR: C:\Qt\5.11\mingw53_32

notifications:
  - provider: GitHubPullRequest

build_script:
  - echo %PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - which git | xargs cygpath -w
  - which unzip | xargs cygpath -w
  - set PATH=C:\Program Files\Git\usr\bin\;%QTDIR%\bin;%MINGW%\bin;C:\msys64\usr\bin;%PATH%
  - which git | xargs cygpath -w
  - which unzip | xargs cygpath -w
test_script:
  - echo "hello"
artifacts:
  - path: test.txt    
