environment:
  global:
    MINGW: C:\Qt\Tools\mingw530_32
    QTDIR: C:\Qt\5.11\mingw53_32

notifications:
  - provider: GitHubPullRequest

build_script:
  - ls installer/trik-studio-offline-*
test_script:
  - echo "hello"
artifacts:
  - path: test.txt    
