name: GHA CI
on:
  push:
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:

      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Create test file
        run: echo hello >> test.txt

      - name: Deploy
#        uses: easingthemes/ssh-deploy@v2.1.5
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.DL_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DL_PASSWORD }}
          local: "test.txt"
          remote: "~/dl/test/test_with_new_name.txt"
