name: GHA CI
on:
  push:
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
#          - qt-version: '5.12.10'
#            mingw-version: 7.3
#            mingw-short-version: 73
#            python-version: 3.8
          - qt-version: '5.15.2'
            mingw-version: 8.1
            mingw-short-version: 81
            python-version: 3.8
    defaults:
      run:
        shell: bash
    steps:

      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Error
        continue-on-error: true
        run: exit 1
        
      - name: Echo
        run: echo After error
