name: GHA CI
on:
  push:
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - qt-version: '5.15.2'
            mingw-version: 8.1
            mingw-short-version: 81
            python-version: 3.8
    defaults:
      run:
        shell: msys2 {0}
    steps:

      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          msystem: MINGW32

      - name: Download packages to msys2
        run: |
            ARCH=32
            PLATFORM=i686
            pacman --verbose --noconfirm -S msys/zlib-devel dos2unix ccache rsync unzip sshpass mingw$ARCH/mingw-w64-$PLATFORM-libzip mingw$ARCH/mingw-w64-$PLATFORM-libusb mingw$ARCH/mingw-w64-$PLATFORM-zlib mingw$ARCH/mingw-w64-$PLATFORM-pkg-config

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          dir: C:\
          version: ${{matrix.qt-version}}
          arch: win32_mingw${{matrix.mingw-short-version}}
          modules: 'qtscript'
          tools: 'tools_ifw,4.1,qt.tools.ifw.41 tools_mingw,${{matrix.mingw-version}},qt.tools.win32_mingw${{matrix.mingw-short-version}}0'
          extra: '--external 7z'
