name: GHA CI
on:
  push:
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:

      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create test file
        run: |
          echo ref is ${{ github.ref }}
          echo head_ref is ${{ github.head_ref }}
          echo base_ref is ${{ github.base_ref }}

      - name: Deploy
        run: sshpass -p ${{ secrets.DL_PASSWORD }} rsync -ve "ssh -o StrictHostKeyChecking=no" installer/iaminstaller.txt ${{ secrets.DL_USERNAME }}@${{ secrets.DL_HOST }}:~/dl/test/
